"""OpenClaw packaging — export a compiled soul to .openclaw/ directory format.

The OpenClaw convention expects:
    .openclaw/
    ├── soul.md          ← Main personality (generated by SoulCraft compiler)
    ├── identity.md      ← Short identity card
    └── agents.md        ← Agent routing directives (optional, for teams)

Team packaging extends this to:
    .openclaw/
    ├── agents.md              ← Team routing (souls, roles, order)
    ├── <soul-id>/
    │   ├── soul.md            ← Team-tuned soul.md
    │   └── identity.md        ← Per-soul identity card
    └── ...

Usage:
    python -m compiler.openclaw souls/linus-torvalds/soul.yaml
    python -m compiler.openclaw --all --output-dir ./export
    python -m compiler.openclaw --team teams/three-kingdoms/team.yaml
"""

import argparse
import sys
from pathlib import Path

from compiler.compile import (
    compile_soul_md,
    find_all_souls,
    load_schema,
    load_soul,
    validate,
)


def generate_identity_md(soul: dict) -> str:
    """Generate identity.md — identity card for the soul."""
    meta = soul["metadata"]
    a = soul["layers"]["A"]
    name = meta["name"]

    identity_desc = a["identity"]["description"].strip()

    lines = [
        f"# {name}",
        "",
        identity_desc,
        "",
        f"- **Soul ID:** {meta['id']}",
        f"- **Version:** {meta['version']}",
        f"- **Extraction:** {meta.get('extraction_method', 'unknown')}",
        f"- **Pipeline:** {meta.get('pipeline_version', 'unknown')}",
    ]

    # Core values summary
    values = a.get("values", [])
    if values:
        lines.append("")
        lines.append("## Core Values")
        for v in values:
            marker = "✓" if v["stance"] == "affirm" else "✗"
            lines.append(f"- {marker} {v['content'].strip()}")

    sources = meta.get("data_sources", [])
    if sources:
        lines.append("")
        lines.append("## Data Sources")
        for src in sources:
            lines.append(f"- **{src['type']}**: {src['description']}")

    return "\n".join(lines) + "\n"


def generate_agents_md(soul: dict) -> str:
    """Generate agents.md — agent routing stub for OpenClaw."""
    meta = soul["metadata"]
    name = meta["name"]

    lines = [
        f"# {name} — Agent Configuration",
        "",
        "## Role",
        f"Base persona: **{name}** (SoulCraft v{meta['version']})",
        "",
        "## Routing",
        "This is a base soul without team-specific routing.",
        "To add team directives, extend this file with:",
        "",
        "```yaml",
        "routing:",
        "  default_handler: self",
        "  delegation_rules: []",
        "```",
        "",
        "## Capabilities",
        f"- Identity-locked responses as {name}",
        "- Full ABCDE personality model",
        "- Provenance-grounded expression",
    ]

    return "\n".join(lines) + "\n"


def generate_team_agents_md(team: dict) -> str:
    """Generate agents.md for a team package — routing and pipeline info."""
    meta = team["metadata"]
    routing = team["routing_strategy"]

    lines = [
        f"# {meta['name']} — Team Agent Configuration",
        "",
        f"**Team ID:** {meta['id']}",
        f"**Version:** {meta['version']}",
        f"**Routing Strategy:** {routing}",
        "",
    ]

    if routing == "hybrid" and "stages" in team:
        lines.append("## Stages")
        lines.append("")
        for i, stage in enumerate(team["stages"], 1):
            lines.append(f"### Stage {i}: {stage['name']} ({stage['type']})")
            if stage["type"] == "iterative":
                lines.append(f"Max iterations: {stage.get('max_iterations', 3)}")
            lines.append("")
            for ref in stage["souls"]:
                soul_entry = next(s for s in team["souls"] if s["soul_ref"] == ref)
                lines.append(f"- **{ref}** — {soul_entry['team_role']}")
            lines.append("")
    else:
        lines.append("## Pipeline Order")
        lines.append("")
        for i, soul_entry in enumerate(team["souls"], 1):
            ref = soul_entry["soul_ref"]
            role = soul_entry["team_role"]
            lines.append(f"{i}. **{ref}** — {role}")
        lines.append("")

    lines.append("## Description")
    lines.append("")
    lines.append(meta.get("description", "").strip())

    return "\n".join(lines) + "\n"


def package_openclaw(soul_path: Path, output_dir: Path | None = None) -> Path:
    """Package a soul.yaml into .openclaw/ directory format."""
    schema = load_schema()
    soul = load_soul(soul_path)

    errors = validate(soul, schema)
    if errors:
        print(f"  ❌ Validation failed ({len(errors)} errors):")
        for err in errors:
            print(f"    - {err}")
        raise SystemExit(1)

    soul_id = soul["metadata"]["id"]
    if output_dir:
        target_dir = output_dir / soul_id / ".openclaw"
    else:
        target_dir = soul_path.parent / ".openclaw"
    target_dir.mkdir(parents=True, exist_ok=True)

    # soul.md
    soul_md = compile_soul_md(soul)
    (target_dir / "soul.md").write_text(soul_md)

    # identity.md
    identity_md = generate_identity_md(soul)
    (target_dir / "identity.md").write_text(identity_md)

    # agents.md
    agents_md = generate_agents_md(soul)
    (target_dir / "agents.md").write_text(agents_md)

    return target_dir


def package_team_openclaw(team_path: Path, output_dir: Path | None = None) -> Path:
    """Package a team.yaml into .openclaw/ directory with per-soul subdirs.

    Supports both sequential and hybrid teams. Uses team_compile to generate
    team-tuned soul.md files, then packages each soul with identity.md.
    """
    from compiler.team_compile import compile_team, load_team

    team = load_team(team_path)
    team_id = team["metadata"]["id"]
    routing = team.get("routing_strategy", "sequential")

    # Compile team first (produces build/ files)
    if output_dir:
        compile_team(team_path, output_dir=output_dir)
        build_dir = output_dir / team_id / "build"
    else:
        compile_team(team_path)
        build_dir = team_path.parent / "build"

    # Determine output directory
    if output_dir:
        target_dir = output_dir / team_id / ".openclaw"
    else:
        target_dir = team_path.parent / ".openclaw"
    target_dir.mkdir(parents=True, exist_ok=True)

    # Team-level agents.md
    agents_md = generate_team_agents_md(team)
    (target_dir / "agents.md").write_text(agents_md)

    # Per-soul subdirectories
    souls_dir = Path(__file__).resolve().parent.parent / "souls"

    if routing == "hybrid" and "stages" in team:
        # Hybrid: read from stage-scoped build dirs
        for stage_idx, stage in enumerate(team["stages"]):
            stage_dir_name = f"{stage_idx:02d}-{stage['name']}"
            for ref in stage["souls"]:
                soul_subdir = target_dir / ref
                soul_subdir.mkdir(parents=True, exist_ok=True)

                team_tuned_md = build_dir / stage_dir_name / ref / "soul.md"
                (soul_subdir / "soul.md").write_text(team_tuned_md.read_text())

                base_soul = load_soul(souls_dir / ref / "soul.yaml")
                identity_md = generate_identity_md(base_soul)
                (soul_subdir / "identity.md").write_text(identity_md)
    else:
        # Sequential: read from flat build dirs
        for soul_entry in team["souls"]:
            ref = soul_entry["soul_ref"]
            soul_subdir = target_dir / ref
            soul_subdir.mkdir(parents=True, exist_ok=True)

            team_tuned_md = build_dir / ref / "soul.md"
            (soul_subdir / "soul.md").write_text(team_tuned_md.read_text())

            base_soul = load_soul(souls_dir / ref / "soul.yaml")
            identity_md = generate_identity_md(base_soul)
            (soul_subdir / "identity.md").write_text(identity_md)

    return target_dir


def main():
    parser = argparse.ArgumentParser(
        description="Package soul.yaml → .openclaw/ directory"
    )
    parser.add_argument("soul_files", nargs="*", help="Path(s) to soul.yaml")
    parser.add_argument("--all", action="store_true", help="Package all souls")
    parser.add_argument("--team", type=Path, help="Path to team.yaml for team packaging")
    parser.add_argument("--output-dir", type=Path, help="Output base directory")
    args = parser.parse_args()

    # Team packaging mode
    if args.team:
        print(f"Packaging team: {args.team}")
        target = package_team_openclaw(args.team, args.output_dir)
        print(f"  📦 Team packaged → {target}/")
        return

    # Base soul packaging mode
    if args.all:
        soul_files = find_all_souls()
    else:
        soul_files = [Path(f) for f in args.soul_files]

    if not soul_files:
        print("No soul files specified. Use --all or provide paths.", file=sys.stderr)
        sys.exit(1)

    for soul_path in soul_files:
        print(f"Packaging: {soul_path}")
        target = package_openclaw(soul_path, args.output_dir)
        print(f"  📦 Packaged → {target}/")


if __name__ == "__main__":
    main()

