"""OpenClaw packaging — export a compiled soul to .openclaw/ directory format.

The OpenClaw convention expects:
    .openclaw/
    ├── soul.md          ← Main personality (generated by SoulCraft compiler)
    ├── identity.md      ← Short identity card
    └── agents.md        ← Agent routing directives (optional, for teams)

Usage:
    python -m compiler.openclaw souls/linus-torvalds/soul.yaml
    python -m compiler.openclaw --all --output-dir ./export
"""

import argparse
import sys
from pathlib import Path

from compiler.compile import (
    compile_soul_md,
    find_all_souls,
    load_schema,
    load_soul,
    validate,
)


def generate_identity_md(soul: dict) -> str:
    """Generate identity.md — identity card for the soul."""
    meta = soul["metadata"]
    a = soul["layers"]["A"]
    name = meta["name"]

    identity_desc = a["identity"]["description"].strip()

    lines = [
        f"# {name}",
        "",
        identity_desc,
        "",
        f"- **Soul ID:** {meta['id']}",
        f"- **Version:** {meta['version']}",
        f"- **Extraction:** {meta.get('extraction_method', 'unknown')}",
        f"- **Pipeline:** {meta.get('pipeline_version', 'unknown')}",
    ]

    # Core values summary
    values = a.get("values", [])
    if values:
        lines.append("")
        lines.append("## Core Values")
        for v in values:
            marker = "✓" if v["stance"] == "affirm" else "✗"
            lines.append(f"- {marker} {v['content'].strip()}")

    sources = meta.get("data_sources", [])
    if sources:
        lines.append("")
        lines.append("## Data Sources")
        for src in sources:
            lines.append(f"- **{src['type']}**: {src['description']}")

    return "\n".join(lines) + "\n"


def generate_agents_md(soul: dict) -> str:
    """Generate agents.md — agent routing stub for OpenClaw."""
    meta = soul["metadata"]
    name = meta["name"]

    lines = [
        f"# {name} — Agent Configuration",
        "",
        "## Role",
        f"Base persona: **{name}** (SoulCraft v{meta['version']})",
        "",
        "## Routing",
        "This is a base soul without team-specific routing.",
        "To add team directives, extend this file with:",
        "",
        "```yaml",
        "routing:",
        "  default_handler: self",
        "  delegation_rules: []",
        "```",
        "",
        "## Capabilities",
        f"- Identity-locked responses as {name}",
        "- Full ABCDE personality model",
        "- Provenance-grounded expression",
    ]

    return "\n".join(lines) + "\n"


def package_openclaw(soul_path: Path, output_dir: Path | None = None) -> Path:
    """Package a soul.yaml into .openclaw/ directory format."""
    schema = load_schema()
    soul = load_soul(soul_path)

    errors = validate(soul, schema)
    if errors:
        print(f"  ❌ Validation failed ({len(errors)} errors):")
        for err in errors:
            print(f"    - {err}")
        raise SystemExit(1)

    soul_id = soul["metadata"]["id"]
    if output_dir:
        target_dir = output_dir / soul_id / ".openclaw"
    else:
        target_dir = soul_path.parent / ".openclaw"
    target_dir.mkdir(parents=True, exist_ok=True)

    # soul.md
    soul_md = compile_soul_md(soul)
    (target_dir / "soul.md").write_text(soul_md)

    # identity.md
    identity_md = generate_identity_md(soul)
    (target_dir / "identity.md").write_text(identity_md)

    # agents.md
    agents_md = generate_agents_md(soul)
    (target_dir / "agents.md").write_text(agents_md)

    return target_dir


def main():
    parser = argparse.ArgumentParser(
        description="Package soul.yaml → .openclaw/ directory"
    )
    parser.add_argument("soul_files", nargs="*", help="Path(s) to soul.yaml")
    parser.add_argument("--all", action="store_true", help="Package all souls")
    parser.add_argument("--output-dir", type=Path, help="Output base directory")
    args = parser.parse_args()

    if args.all:
        soul_files = find_all_souls()
    else:
        soul_files = [Path(f) for f in args.soul_files]

    if not soul_files:
        print("No soul files specified. Use --all or provide paths.", file=sys.stderr)
        sys.exit(1)

    for soul_path in soul_files:
        print(f"Packaging: {soul_path}")
        target = package_openclaw(soul_path, args.output_dir)
        print(f"  📦 Packaged → {target}/")


if __name__ == "__main__":
    main()
